apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-ui
spec:
  selector:
    matchLabels:
      app: flask-demo-ui
  template:
    metadata:
      labels:
        app: flask-demo-ui
    spec:
      containers:
        - name: flask-demo-ui
          image: taloricag/flask-sw-demo-ui:lateset
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: otel-collector.open-telemetry:11800
            - name: SW_AGENT_PROTOCOL
              value: grpc
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-shop
spec:
  selector:
    matchLabels:
      app: flask-demo-shop
  template:
    metadata:
      labels:
        app: flask-demo-shop
    spec:
      containers:
        - name: flask-demo-shop
          image: taloricag/flask-sw-demo-shop:0.1.0
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: otel-collector.open-telemetry:11800
            - name: SW_AGENT_PROTOCOL
              value: grpc
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-store
spec:
  selector:
    matchLabels:
      app: flask-demo-store
  template:
    metadata:
      labels:
        app: flask-demo-store
    spec:
      containers:
        - name: flask-demo-store
          image: taloricag/flask-sw-demo-store:0.1.0
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: otel-collector.open-telemetry:11800
            - name: SW_AGENT_PROTOCOL
              value: grpc
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: taloricag/flask-sw-demo-loadgenerator:0.1.0
          env:
            - name: FRONTEND_ADDR
              value: webshop:8090
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: otel-collector.open-telemetry:11800
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=loadgenerator
            - name: USERS
              value: '1'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ui-svc
spec:
  selector:
    app: flask-demo-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-svc
spec:
  selector:
    app: flask-demo-shop
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-store-svc
spec:
  selector:
    app: flask-demo-store
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
